title: Muki
description: > # this means to ignore newlines until "baseurl:"
  Hi there :) I'm a developer, musician and "nice-to-have-around" guy.
  This site contains blog posts written by me and information about me.
  Don't hesitate to contact.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://muki.rocks" # the base hostname & protocol for your site, e.g. http://example.com


# Jekyll
permalink:   /:title/
markdown:    kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
highlighter: rouge

destination: _site
paginate: 3

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

author:
  name: Muki
  avatar: profile.png
  email: whorocks@muki.rocks
  github_username: muuki88
  twitter_username: muuki88
  linkedin_username: nepomuk-seiler-59564b98
  # facebook_username:

# Google Analytics
google_analytics: UA-27053898-1


# Build settings
theme: minima
timezone: "Europe/Berlin"
encoding: utf-8
gems:
  - minima
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site
  - CNAME
  - LICENSE
