# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Muki's Website
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://muki.rocks" # the base hostname & protocol for your site, e.g. http://example.com
logo: me.png

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# sidebar_background_image: images/home.png

author:
  name: Muki
  email: whorocks@muki.rocks
  github: muuki88
  twitter: muuki88
  linkedin: nepomuk-seiler-59564b98
  bio: It's me. Muki!
  email_md5: cb0364b3138736a3cb99eea5899935d8

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
# email:              whorocks@muki.rocks
# google.plus:        nepomuk.seiler
# twitter:            muuki88
# github:             muuki88
# stackoverflow:      709351/muki
# linkedin:           nepomuk-seiler-59564b98
# xing:               Nepomuk_Seiler
# soundcloud:         muuki88
# keybase:            muki

# Build settings
theme: minima
timezone: "Europe/Berlin"
encoding: utf-8
gems:
  - minima
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - pygments.rb
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site
  - src
  - vendor
  - CNAME
  - LICENSE
  - Rakefile
  - .sass-cache
